import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/router";

import classToggle from "../../contexts/classtoggle";
import SingleSelectionMenu from "../../contexts/singleSelectionMenu";

import Tombol from "../../components/Tombol";
import Layout from "../../components/layout";
import BorderBottomMenu from "../../components/menu/borderBottom";

import styles from "../../styles/detailPage.module.css";

export default function Detail() {
  const router = useRouter();
  const { JudulKomik } = router.query;
  const [menuSelection, setMenuSelection] = useState(1);

  const dataSementara = [
    { judul: "Chapter 1", tanggal: "10/12/2022" },
    { judul: "Chapter 2", tanggal: "10/12/2022" },
    { judul: "Chapter 3", tanggal: "10/12/2022" },
    { judul: "Chapter 4", tanggal: "10/12/2022" },
  ];

  return (
    <>
      <Head>
        <title>KomikOI | Baca Manga, Manhua, Manhwa Bahasa Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <Menu states={[menuSelection, setMenuSelection]} />
        <KontenBox data={dataSementara} kontenType={menuSelection} />
        <section></section>
      </Layout>
    </>
  );
}

function Banner() {
  return (
    <div className={styles.banner}>
      <div className={styles.bannerImage}>
        <Image
          src={`/images/cover.jpg`}
          layout="fill"
          objectFit="cover"
          alt="yuanzun"
          priority={true}
        />
      </div>
      <div className={styles.infoKonten}>
        <h2 className={styles.infoJudul}>Spare, Me Great Lord</h2>
        <div className={styles.infoGenre}>
          <Tombol className={styles.genreBox}>Aksi</Tombol>
          <Tombol className={styles.genreBox}>Fantasi</Tombol>
          <Tombol className={styles.genreBox}>Kultivasi</Tombol>
        </div>
      </div>
    </div>
  );
}

function Menu({ states }) {
  const [menuSelection, setMenuSelection] = states;

  // OnClick (Tombol Chapter)
  const handleTombolChapter = () => setMenuSelection(1);

  // OnClick (Tombol Sinopsis)
  const handleTombolSinopsis = () => setMenuSelection(0);

  return (
    <SingleSelectionMenu activeIndex={1}>
      <BorderBottomMenu text="Sinopsis" onClick={handleTombolSinopsis} />
      <BorderBottomMenu text="Chapter" onClick={handleTombolChapter} />
    </SingleSelectionMenu>
  );
}

function KontenBox({ data, kontenType }) {
  return (
    <div className={`${styles.kontenBox} _${kontenType} `}>
      <Chapter data={data} />
      <Sinopsis />
    </div>
  );
}

function Chapter({ data }) {
  const [isASC, setASC] = useState(0);

  const toggleASC = classToggle(isASC);
  const toggleDESC = classToggle(!isASC);

  const handleASC = () => setASC(1);
  const handleDESC = () => setASC(0);

  const ElemenItems = data.map((value, index) => {
    return (
      <li className={styles.Items} key={index}>
        <div className={styles.chapter}>{value.judul}</div>
        <div className={styles.tanggalRilis}>{value.tanggal}</div>
      </li>
    );
  });

  return (
    <div className={styles.chapterBox}>
      <div className={styles.Sort}>
        <div className={styles.totalChapter}>Total {data.length} Chapter</div>
        <div className={`${styles.sortMenu} no-select`}>
          <div className={`ASC ${toggleASC}`} onClick={handleASC}>
            <span className={styles.sortType}>Naik</span>
          </div>
          <span className="hr" />
          <div className={`DESC ${toggleDESC}`} onClick={handleDESC}>
            <span className={styles.sortType}>Turun</span>
          </div>
        </div>
      </div>
      <ul className={`${styles.chapterList} _${isASC}`}>{ElemenItems}</ul>
    </div>
  );
}

function Sinopsis() {
  return (
    <div className={styles.sinopsisBox}>
      <div className={styles.sinopsis}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi quia odio
        vero mollitia nihil dolor quis dolores reprehenderit provident non
        error, libero eligendi ipsa assumenda.
      </div>
    </div>
  );
}
