import Head from "next/head";
import { useRouter } from "next/router";
import { useRef, createContext } from "react";
import Menu from "../../components/DetailPage/Menu";
import Banner from "../../components/DetailPage/Banner";
import Chapter from "../../components/DetailPage/Chapter";
import Sinopsis from "../../components/DetailPage/Sinopsis";
import styles from "../../styles/detailPage.module.css";

export async function getServerSideProps() {
  const DataChapter = [
    { judul: "Chapter 1", tanggal: "10/12/2022" },
    { judul: "Chapter 2", tanggal: "10/12/2022" },
    { judul: "Chapter 3", tanggal: "10/12/2022" },
    { judul: "Chapter 4", tanggal: "10/12/2022" },
  ];

  return {
    props: {
      DataChapter,
    },
  };
}

export const DetailContext = createContext();

export default function Detail(props) {
  const DataChapter = props.DataChapter;
  const router = useRouter();
  const { JudulKomik } = router.query;

  // untuk toggle kontenBox sinopsis/chapter
  const kontenBoxRef = useRef();

  return (
    <>
      <Head>
        <title>KomikOI | Baca Manga, Manhua, Manhwa Bahasa Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailContext.Provider
        value={{ DataChapter: DataChapter, kontenBoxRef: kontenBoxRef }}
      >
        <Banner />
        <Menu />
        <div className={`${styles.kontenBox}`} ref={kontenBoxRef}>
          <Chapter />
          <Sinopsis />
        </div>
      </DetailContext.Provider>
    </>
  );
}
