import Head from "next/head";
import Image from "next/image";
import React, { useRef } from "react";
import { useRouter } from "next/router";

import SingleSelectionMenu from "../../libs/singleSelectionMenu";

import FillText from "../../components/menu/filltext";
import BorderBottomMenu from "../../components/menu/borderBottom";
import Tombol from "../../components/Tombol";
import Layout from "../../components/layout";

import styles from "../../styles/detailPage.module.css";

const MemorizeTombol = React.memo(Tombol);

export async function getServerSideProps() {
  const dataSementara = [
    { judul: "Chapter 1", tanggal: "10/12/2022" },
    { judul: "Chapter 2", tanggal: "10/12/2022" },
    { judul: "Chapter 3", tanggal: "10/12/2022" },
    { judul: "Chapter 4", tanggal: "10/12/2022" },
  ];

  return {
    props: {
      dataSementara,
    },
  };
}

export default function Detail(props) {
  const dataSementara = props.dataSementara;
  const router = useRouter();
  const { JudulKomik } = router.query;

  // untuk toggle kontenBox sinopsis dan chapter
  const kontenBoxRef = useRef();

  return (
    <>
      <Head>
        <title>KomikOI | Baca Manga, Manhua, Manhwa Bahasa Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <Menu kontenBoxRef={kontenBoxRef} />
        <KontenBox data={dataSementara} kontenBoxRef={kontenBoxRef} />
        <section></section>
      </Layout>
    </>
  );
}

function Banner() {
  return (
    <div className={styles.banner}>
      <div className={styles.bannerImage}>
        <Image
          src={`/images/cover.jpg`}
          layout="fill"
          objectFit="cover"
          alt="yuanzun"
          priority={true}
        />
      </div>
      <div className={styles.infoKonten}>
        <h2 className={styles.infoJudul}>Spare, Me Great Lord</h2>
        <div className={styles.infoGenre}>
          <Tombol className={styles.genreBox} text="Aksi" />
          <Tombol className={styles.genreBox} text="Fantasi" />
          <Tombol className={styles.genreBox} text="Kultivasi" />
        </div>
      </div>
    </div>
  );
}

function Menu({ kontenBoxRef }) {
  const handleChange = (value) => {
    kontenBoxRef.current.classList.remove("Chapter");
    kontenBoxRef.current.classList.remove("Sinopsis");
    kontenBoxRef.current.classList.add(value);
  };

  return (
    <SingleSelectionMenu
      activeIndex={1}
      classTambahan={styles.menu}
      customOnChange={handleChange}
    >
      <BorderBottomMenu text="Sinopsis" />
      <BorderBottomMenu text="Chapter" />
    </SingleSelectionMenu>
  );
}

function KontenBox({ data, kontenBoxRef }) {
  return (
    <div className={`${styles.kontenBox}`} ref={kontenBoxRef}>
      <Chapter data={data} />
      <Sinopsis />
    </div>
  );
}

function Chapter({ data }) {
  const chapterBoxRef = useRef();

  const handleChange = (value) => {
    chapterBoxRef.current.classList.remove("Turun");
    chapterBoxRef.current.classList.remove("Naik");
    chapterBoxRef.current.classList.add(value);
  };

  const ElemenItems = data.map((value, index) => {
    return (
      <li className={styles.Items} key={index}>
        <div className={styles.chapter}>{value.judul}</div>
        <div className={styles.tanggalRilis}>{value.tanggal}</div>
      </li>
    );
  });

  return (
    <div className={styles.chapterBox}>
      <div className={styles.Sort}>
        <div className={styles.totalChapter}>Total {data.length} Chapter</div>
        <div className={`${styles.sortMenu} no-select`}>
          <SingleSelectionMenu
            indexKey={1}
            activeIndex={2}
            customOnChange={handleChange}
          >
            <FillText text="Naik" classTambahan={styles.tombolSort} />
            <div className="hr" bukantombol={1} />
            <FillText text="Turun" classTambahan={styles.tombolSort} />
          </SingleSelectionMenu>
        </div>
      </div>
      <ul className={`${styles.chapterList} Turun`} ref={chapterBoxRef}>
        {ElemenItems}
      </ul>
    </div>
  );
}

function Sinopsis() {
  return (
    <div className={styles.sinopsisBox}>
      <div className={styles.sinopsis}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi quia odio
        vero mollitia nihil dolor quis dolores reprehenderit provident non
        error, libero eligendi ipsa assumenda.
      </div>
    </div>
  );
}
