import Image from "next/image";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../../styles/detail.module.css";

import Tombol from "../../components/Tombol";
import { Star } from "../../components/Icons";
import Layout from "../../components/layout";

export default function Detail() {
  const router = useRouter();
  const { plink } = router.query;
  return (
    <>
      <Head>
        <title>KomikOI | Baca Manga, Manhua, Manhwa Bahasa Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.banner}>
          <div className={styles.bannerImage}>
            <Image
              src={`/images/cover.jpg`}
              layout="fill"
              objectFit="cover"
              alt="yuanzun"
              priority={true}
            />
          </div>
          <div className={styles.infoKonten}>
            <h2 className={styles.infoTitle}>Spare, Me Great Lord</h2>
            <div className={styles.infoTipe}>Manhua</div>
          </div>
        </div>
        <section>
          <div className={styles.tombols}>
            <Tombol link="anjing" color="oren" className={styles.tombolFavorit}>
              <Star width={15} height={15} />
              Favorit
            </Tombol>
            <Tombol
              link="anjay"
              color="biru"
              className={styles.tombolMulaiBaca}
            >
              Mulai Membaca
            </Tombol>
          </div>
          <div className={styles.infoKonten2}>
            <div className={styles.infoGenre}>
              <Tombol className={styles.genre}>Action</Tombol>
              <Tombol className={styles.genre}>Kultivasi</Tombol>
              <Tombol className={styles.genre}>Fantasy</Tombol>
            </div>
            <div className={styles.infoDekripsi}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti
              minus optio et nulla, expedita unde quam dolore totam qui ipsa eum
              impedit voluptatem rem fuga.
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}
