import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>KomikOI | Baca Manga, Manhua, Manhwa Bahasa Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.KontenBox}>
          <div className={styles.header}>
            <h1>Komik Populer</h1>
            <div className={styles.tombolLagi}>Lagi</div>
          </div>
          <div className={styles.thumbnailList}>
            <Thumbnail />
            <Thumbnail />
            <Thumbnail />
          </div>
        </section>
      </main>
    </div>
  );
}

function Thumbnail() {
  return (
    <div className={styles.thumbnail}>
      <div className={styles.thumbnailImage}>
        <Image src="/images/cover.jpg" layout="fill" />
      </div>
      <div className={styles.description}>
        <div className={styles.infoTitle}>Yuan Zun</div>
      </div>
    </div>
  );
}
