import Head from "next/head";
import Slideshow from "../components/SlideShow";
import ListHeader from "../components/ListHeader";
import ThumbnailList from "../components/ThumbnailList";
import styles from "../styles/Home.module.css";
import { isTablet } from "../libs/mediaquery";

export async function getServerSideProps() {
  return {
    props: {
      DataKonten: [
        {
          judul: "Spare Me, Great Lord !",
          foto: "cover.jpg",
          link: "spare-me-great-lord",
        },
        { judul: "Yuan Zun", foto: "cover2.jpg", link: "yuan-zun" },
        {
          judul: "Wo Shi Da Shen Xian",
          foto: "cover3.jpg",
          link: "wo-shi-da-shen-xian",
        },
      ],
      DataSlideshow: [
        {
          judul: "Spare Me, Great Lord !",
          foto: "cover.jpg",
          link: "spare-me-great-lord",
        },
        { judul: "Yuan Zun", foto: "cover2.jpg", link: "yuan-zun" },
        {
          judul: "Wo Shi Da Shen Xian",
          foto: "cover3.jpg",
          link: "wo-shi-da-shen-xian",
        },
      ],
    },
  };
}

export default function Home({ DataKonten, DataSlideshow }) {
  const SlideshowConfig = isTablet
    ? { slidesPerView: 1.5, navigation: true }
    : { slidesPerView: 1, navigation: false };

  return (
    <>
      <Head>
        <title>KomikOI | Baca Manga, Manhua, Manhwa Bahasa Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slideshow Data={DataSlideshow} SlideshowConfig={SlideshowConfig} />
      <section className={styles.KontenBox}>
        <ListHeader teks="Terakhir diperbarui" />
        <ThumbnailList Data={DataKonten} />
      </section>
    </>
  );
}
